#!/usr/bin/env python3

# You can move this file to your ~/.local/bin or another path

import sys
import os

# Change this variable to the shell location
SHELL_CODE_PATH = os.path.expanduser("~/.config/shell")
sys.path.append(SHELL_CODE_PATH)
from main import run

if __name__ == "__main__":
    run(sys.argv)