# reload
bind = SUPER + SHIFT, r, reload_config

bind = SUPER, T, spawn, ghostty
bind = SUPER, R, spawn, fuzzel
bind = SUPER, E, spawn, nautilus

bind = SUPER, m, quit
bind = SUPER, q, killclient

bind = SUPER, O, toggleoverview
bind = SUPER, V, togglefloating
bind = SUPER, f, togglefullscreen
bind = SUPER + SHIFT, f, togglemaximizescreen
bind = SUPER + ALT, f, togglefakefullscreen
bind = ALT, z, toggle_scratchpad

# focus workspace
bind = SUPER, 1, view, 1
bind = SUPER, 2, view, 2
bind = SUPER, 3, view, 3
bind = SUPER, 4, view, 4
bind = SUPER, 5, view, 5
bind = SUPER, 6, view, 6
bind = SUPER, 7, view, 7
bind = SUPER, 8, view, 8
bind = SUPER, 9, view, 9

# move to workspace
bind = SUPER + SHIFT, 1, tag, 1
bind = SUPER + SHIFT, 2, tag, 2
bind = SUPER + SHIFT, 3, tag, 3
bind = SUPER + SHIFT, 4, tag, 4
bind = SUPER + SHIFT, 5, tag, 5
bind = SUPER + SHIFT, 6, tag, 6
bind = SUPER + SHIFT, 7, tag, 7
bind = SUPER + SHIFT, 8, tag, 8
bind = SUPER + SHIFT, 9, tag, 9

# resize
bind=SUPER,Down,resizewin,+0,+50
bind=SUPER,Up,resizewin,+0,-50
bind=SUPER,Left,resizewin,-50,+0
bind=SUPER,Right,resizewin,+50,+0
