source = ~/.config/mango/mouse.conf
source = ~/.config/mango/bindings.conf
source = ~/.config/mango/layout.conf
source = ~/.config/mango/decorations.conf
source = ~/.config/mango/execs.conf
source-optional = ~/.config/mango/theme.conf
