borderpx = 2
gappoh = 20
gappov = 20

shadows = 1

border_radius = 12

unfocused_opacity = 0.9

animation_type_open = slide
animation_type_close = zoom
animation_duration_open = 300
animation_duration_close = 200
